
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample set of NodeJS functions

# Enabling CORS just in case (this is bad for production)
Globals:
  Function:
    CodeUri: build/
    Runtime: nodejs12.x
    Timeout: 300
  Api:
    Cors:
      AllowCredentials: false
      AllowHeaders: "'*'"
      AllowMethods: "'GET,PUT,POST'"
      AllowOrigin: "'*'"

Resources:
  Hello1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: helloFunction1.handler
      Runtime: nodejs12.x
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Characters:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello1
            Method: get
  Hello2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: helloFunction2.handler
      Runtime: nodejs12.x
      MemorySize: 512
      Events:
        Characters:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello2
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Hello1Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello 1 function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello1/"
  Hello1Function:
    Description: "Tryout Lambda Function ARN"
    Value: !GetAtt Hello1Function.Arn
  Hello1FunctionIamRole:
    Description: "Implicit IAM Role created for Hello 1 function"
    Value: !GetAtt Hello1FunctionRole.Arn
  Hello2Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello 2 function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello2/"
  Hello2Function:
    Description: "Tryout Lambda Function ARN"
    Value: !GetAtt Hello2Function.Arn
  Hello2FunctionIamRole:
    Description: "Implicit IAM Role created for Hello 2 function"
    Value: !GetAtt Hello2FunctionRole.Arn